#:schema node_modules/wrangler/config-schema.json
name = "email-calendar"
main = "src/index.ts"
compatibility_date = "2024-12-25"
compatibility_flags = ["nodejs_compat"]

[[send_email]]
name = "PURDUE_EMAIL"
destination_address = "rayhan@purdue.edu"

[observability]
enabled = false
